/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package my.example.hue;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Ct extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4424686370072409996L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Ct\",\"namespace\":\"my.example.hue\",\"fields\":[{\"name\":\"min\",\"type\":\"long\"},{\"name\":\"max\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Ct> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Ct> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Ct> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Ct> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Ct> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Ct to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Ct from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Ct instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Ct fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  public long min;
  public long max;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Ct() {}

  /**
   * All-args constructor.
   * @param min The new value for min
   * @param max The new value for max
   */
  public Ct(java.lang.Long min, java.lang.Long max) {
    this.min = min;
    this.max = max;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return min;
    case 1: return max;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: min = (java.lang.Long)value$; break;
    case 1: max = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'min' field.
   * @return The value of the 'min' field.
   */
  public long getMin() {
    return min;
  }


  /**
   * Sets the value of the 'min' field.
   * @param value the value to set.
   */
  public void setMin(long value) {
    this.min = value;
  }

  /**
   * Gets the value of the 'max' field.
   * @return The value of the 'max' field.
   */
  public long getMax() {
    return max;
  }


  /**
   * Sets the value of the 'max' field.
   * @param value the value to set.
   */
  public void setMax(long value) {
    this.max = value;
  }

  /**
   * Creates a new Ct RecordBuilder.
   * @return A new Ct RecordBuilder
   */
  public static my.example.hue.Ct.Builder newBuilder() {
    return new my.example.hue.Ct.Builder();
  }

  /**
   * Creates a new Ct RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Ct RecordBuilder
   */
  public static my.example.hue.Ct.Builder newBuilder(my.example.hue.Ct.Builder other) {
    if (other == null) {
      return new my.example.hue.Ct.Builder();
    } else {
      return new my.example.hue.Ct.Builder(other);
    }
  }

  /**
   * Creates a new Ct RecordBuilder by copying an existing Ct instance.
   * @param other The existing instance to copy.
   * @return A new Ct RecordBuilder
   */
  public static my.example.hue.Ct.Builder newBuilder(my.example.hue.Ct other) {
    if (other == null) {
      return new my.example.hue.Ct.Builder();
    } else {
      return new my.example.hue.Ct.Builder(other);
    }
  }

  /**
   * RecordBuilder for Ct instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Ct>
    implements org.apache.avro.data.RecordBuilder<Ct> {

    private long min;
    private long max;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(my.example.hue.Ct.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.min)) {
        this.min = data().deepCopy(fields()[0].schema(), other.min);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.max)) {
        this.max = data().deepCopy(fields()[1].schema(), other.max);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Ct instance
     * @param other The existing instance to copy.
     */
    private Builder(my.example.hue.Ct other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.min)) {
        this.min = data().deepCopy(fields()[0].schema(), other.min);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.max)) {
        this.max = data().deepCopy(fields()[1].schema(), other.max);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'min' field.
      * @return The value.
      */
    public long getMin() {
      return min;
    }


    /**
      * Sets the value of the 'min' field.
      * @param value The value of 'min'.
      * @return This builder.
      */
    public my.example.hue.Ct.Builder setMin(long value) {
      validate(fields()[0], value);
      this.min = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'min' field has been set.
      * @return True if the 'min' field has been set, false otherwise.
      */
    public boolean hasMin() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'min' field.
      * @return This builder.
      */
    public my.example.hue.Ct.Builder clearMin() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'max' field.
      * @return The value.
      */
    public long getMax() {
      return max;
    }


    /**
      * Sets the value of the 'max' field.
      * @param value The value of 'max'.
      * @return This builder.
      */
    public my.example.hue.Ct.Builder setMax(long value) {
      validate(fields()[1], value);
      this.max = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'max' field has been set.
      * @return True if the 'max' field has been set, false otherwise.
      */
    public boolean hasMax() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'max' field.
      * @return This builder.
      */
    public my.example.hue.Ct.Builder clearMax() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Ct build() {
      try {
        Ct record = new Ct();
        record.min = fieldSetFlags()[0] ? this.min : (java.lang.Long) defaultValue(fields()[0]);
        record.max = fieldSetFlags()[1] ? this.max : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Ct>
    WRITER$ = (org.apache.avro.io.DatumWriter<Ct>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Ct>
    READER$ = (org.apache.avro.io.DatumReader<Ct>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.min);

    out.writeLong(this.max);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.min = in.readLong();

      this.max = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.min = in.readLong();
          break;

        case 1:
          this.max = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










