/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package my.example.hue;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Streaming extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3898254936730474614L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Streaming\",\"namespace\":\"my.example.hue\",\"fields\":[{\"name\":\"renderer\",\"type\":\"boolean\"},{\"name\":\"proxy\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Streaming> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Streaming> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Streaming> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Streaming> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Streaming> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Streaming to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Streaming from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Streaming instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Streaming fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  public boolean renderer;
  public boolean proxy;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Streaming() {}

  /**
   * All-args constructor.
   * @param renderer The new value for renderer
   * @param proxy The new value for proxy
   */
  public Streaming(java.lang.Boolean renderer, java.lang.Boolean proxy) {
    this.renderer = renderer;
    this.proxy = proxy;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return renderer;
    case 1: return proxy;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: renderer = (java.lang.Boolean)value$; break;
    case 1: proxy = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'renderer' field.
   * @return The value of the 'renderer' field.
   */
  public boolean getRenderer() {
    return renderer;
  }


  /**
   * Sets the value of the 'renderer' field.
   * @param value the value to set.
   */
  public void setRenderer(boolean value) {
    this.renderer = value;
  }

  /**
   * Gets the value of the 'proxy' field.
   * @return The value of the 'proxy' field.
   */
  public boolean getProxy() {
    return proxy;
  }


  /**
   * Sets the value of the 'proxy' field.
   * @param value the value to set.
   */
  public void setProxy(boolean value) {
    this.proxy = value;
  }

  /**
   * Creates a new Streaming RecordBuilder.
   * @return A new Streaming RecordBuilder
   */
  public static my.example.hue.Streaming.Builder newBuilder() {
    return new my.example.hue.Streaming.Builder();
  }

  /**
   * Creates a new Streaming RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Streaming RecordBuilder
   */
  public static my.example.hue.Streaming.Builder newBuilder(my.example.hue.Streaming.Builder other) {
    if (other == null) {
      return new my.example.hue.Streaming.Builder();
    } else {
      return new my.example.hue.Streaming.Builder(other);
    }
  }

  /**
   * Creates a new Streaming RecordBuilder by copying an existing Streaming instance.
   * @param other The existing instance to copy.
   * @return A new Streaming RecordBuilder
   */
  public static my.example.hue.Streaming.Builder newBuilder(my.example.hue.Streaming other) {
    if (other == null) {
      return new my.example.hue.Streaming.Builder();
    } else {
      return new my.example.hue.Streaming.Builder(other);
    }
  }

  /**
   * RecordBuilder for Streaming instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Streaming>
    implements org.apache.avro.data.RecordBuilder<Streaming> {

    private boolean renderer;
    private boolean proxy;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(my.example.hue.Streaming.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.renderer)) {
        this.renderer = data().deepCopy(fields()[0].schema(), other.renderer);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.proxy)) {
        this.proxy = data().deepCopy(fields()[1].schema(), other.proxy);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Streaming instance
     * @param other The existing instance to copy.
     */
    private Builder(my.example.hue.Streaming other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.renderer)) {
        this.renderer = data().deepCopy(fields()[0].schema(), other.renderer);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.proxy)) {
        this.proxy = data().deepCopy(fields()[1].schema(), other.proxy);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'renderer' field.
      * @return The value.
      */
    public boolean getRenderer() {
      return renderer;
    }


    /**
      * Sets the value of the 'renderer' field.
      * @param value The value of 'renderer'.
      * @return This builder.
      */
    public my.example.hue.Streaming.Builder setRenderer(boolean value) {
      validate(fields()[0], value);
      this.renderer = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'renderer' field has been set.
      * @return True if the 'renderer' field has been set, false otherwise.
      */
    public boolean hasRenderer() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'renderer' field.
      * @return This builder.
      */
    public my.example.hue.Streaming.Builder clearRenderer() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'proxy' field.
      * @return The value.
      */
    public boolean getProxy() {
      return proxy;
    }


    /**
      * Sets the value of the 'proxy' field.
      * @param value The value of 'proxy'.
      * @return This builder.
      */
    public my.example.hue.Streaming.Builder setProxy(boolean value) {
      validate(fields()[1], value);
      this.proxy = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'proxy' field has been set.
      * @return True if the 'proxy' field has been set, false otherwise.
      */
    public boolean hasProxy() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'proxy' field.
      * @return This builder.
      */
    public my.example.hue.Streaming.Builder clearProxy() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Streaming build() {
      try {
        Streaming record = new Streaming();
        record.renderer = fieldSetFlags()[0] ? this.renderer : (java.lang.Boolean) defaultValue(fields()[0]);
        record.proxy = fieldSetFlags()[1] ? this.proxy : (java.lang.Boolean) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Streaming>
    WRITER$ = (org.apache.avro.io.DatumWriter<Streaming>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Streaming>
    READER$ = (org.apache.avro.io.DatumReader<Streaming>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeBoolean(this.renderer);

    out.writeBoolean(this.proxy);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.renderer = in.readBoolean();

      this.proxy = in.readBoolean();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.renderer = in.readBoolean();
          break;

        case 1:
          this.proxy = in.readBoolean();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










